import "./globals.css";
import { Quicksand } from "next/font/google";
import Header from "@/components/Header";
import NavBottom from "@/components/NavBottom";
import { CartProvider } from "@/context/CartContext";
import ActiveSectionContextProvider from "@/context/ActiveSectionContext";
import { Toaster } from "react-hot-toast";
import ThemeToggle from "@/components/ThemeToggle";
import ThemeContextProvider from "@/context/ThemeContext";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["300", "700"],
});

export const metadata = {
  title: "FIKA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${quicksand.className} bg-sky-400 relative dark:bg-black
        `}
      >
        <ThemeContextProvider>
        <ActiveSectionContextProvider>
          <CartProvider>
            <Header />
            <Toaster position="top-right"/>
            {children} 
            <ThemeToggle/>
            <NavBottom />
          </CartProvider>
        </ActiveSectionContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
