import "./globals.css";
import { Quicksand } from "next/font/google";
import Header from "@/components/Header";
import NavBottom from "@/components/NavBottom";
import { CartProvider } from "@/context/CartContext";
import ActiveSectionContextProvider from "@/context/ActiveSectionContext";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["300", "700"],
});

export const metadata = {
  title: "FIKA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${quicksand.className} bg-sky-400 relative
        `}
      >
        <ActiveSectionContextProvider>
          <CartProvider>
            <Header />
            {children}
            <NavBottom />
          </CartProvider>
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
