import "./globals.css";
import { Inter } from "next/font/google";
import BigBulle from "@/components/BigBulleImg";
import HeroP from "@/components/HeroP";
import ContainerMaxWidth from "@/components/ContainerMaxWidth";
import NavBottom from "@/components/NavBottom";
import NavTop from "@/components/NavTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gray-50  relative
         h-[5000] pt-28 sm:pt-36`}
      >
        <div
          className="bg-blue-100 absolute top-[-6rem] -z-10 right-[11rem]
        h-[31.25rem] w-[31.25rem] rounded-full blur-[10rem] sm:w-[68.75rem]"
        ></div>
        <div
          className="bg-yellow-90 absolute top-[-1rem] -z-10 left-[-35rem]
        h-[31.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem]
        md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem]"
        ></div>

        <NavTop />
        
        <ContainerMaxWidth>
          {children}   
          <HeroP />
          <BigBulle />
        </ContainerMaxWidth>

        <NavBottom />
      </body>
    </html>
  );
}
